# Generated by Django 4.2.1 on 2023-05-12 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='contactos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Clave_cliente', models.CharField(max_length=50)),
                ('Nombre_Contacto', models.CharField(max_length=50)),
                ('Correo', models.CharField(max_length=50)),
                ('Telefono', models.CharField(max_length=50)),
            ],
        ),
    ]
